# -----------------------------------------------------------------------------
# .SYNOPSIS
#   This is the main pipeline for ADO Deployment. 
#   The main pipeline will orchestrate the build and deploy to environments. 

# .DESCRIPTION
#   This pipeline will perform setup tasks for the image by:
#   1. Copy and Publish Build Artifacts - Terraform scripts.
#   2. Create Storage Account or Terraform State - https://docs.microsoft.com/en-us/azure/terraform/terraform-backend
#   3. Find and replace token (variables) in .tf and .tfvars files.
#   4. Setup Terraform
#   5. Plan and Apply Terraform

# .ASSUMPTIONS:
#     1. You are referencing this template from an ado pipeline

# .NOTES
#     File Name      : azure-pipelines.yml
#     Prerequisite   : ADO Multi-Stage Yaml Pipeline
# -----------------------------------------------------------------------------

name: ADO-Infra-$(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
      - README.md
      - azure-pipelines.sh

variables:
  - group: ado_dev_vars
  
  - name: ado_agent_pool
    value: 'Azure Pipelines'
  - name: ado_service_connection_name
    value: 'sc-ado-self-hosted-agent-azure-subscription'

stages: 
  - stage: Build
    displayName: Build  
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-18.04
        steps:
        - task: AzureCLI@1
          displayName: 'Azure CLI - Deploy Terraform State Storage Account'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              # Create Azure resource group
              az group create --location $(location) --name $(terraformstoragerg)
              
              # Create Azure Storage Account
              az storage account create --name $(terraformstorageaccount) --resource-group $(terraformstoragerg) --location $(location) --sku Standard_LRS --kind StorageV2
              
              # Create Storage Container
              az storage container create --name terraform --account-name $(terraformstorageaccount)
              
              # Get Storage Key
              set KEY=$(az storage account keys list -g $(terraformstoragerg) -n $(terraformstorageaccount) --query "[0].value" -o tsv)
              
              # Set Storage Key as Variable for later use
              echo "##vso[task.setvariable variable=storagekey]$KEY"

        - task: CopyFiles@2
          displayName: 'Copy Terraform Var Files to Artifacts Staging Directory'
          inputs:
            contents: '**/*.tfvars'
            TargetFolder: '$(build.artifactstagingdirectory)'
            
        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform vars file'
          inputs:
            targetFiles: '**/*.tfvars'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform 0.12.24'
          inputs:
            terraformVersion: 0.12.24
  
        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : init'
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: 'ado/terraform.tfstate'

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : plan'
          inputs:
            command: plan
            commandOptions: '-out=terraform$(Build.BuildId).tfplan'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: 'ado/terraform.tfstate'
            
        - task: AzureCLI@1
          displayName: 'Azure CLI - Upload TF Plan to Storage Account'
          inputs:
            azureSubscription: ${{ variables.ado_service_connection_name }}
            scriptLocation: inlineScript
            inlineScript: |
              # Upload TF Plan file to Azure Storage
              az storage blob upload --account-name '$(terraformstorageaccount)' --account-key $(storagekey) --container-name 'terraform' --name 'ado/plans/terraform$(Build.BuildId).tfplan' --file 'terraform$(Build.BuildId).tfplan' --auth-mode key
              
        - task: CopyFiles@2
          displayName: 'Copy Terraform Files to Artifacts Staging Directory'
          inputs:
            contents: '**/*.tf'
            TargetFolder: '$(build.artifactstagingdirectory)'

        - task: CopyFiles@2
          displayName: 'Copy Scripts Directory Files to Artifacts Staging Directory'
          inputs:
            contents: '**/scripts/**'
            TargetFolder: '$(build.artifactstagingdirectory)'

        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifact: infra'
          inputs:
            ArtifactName: infra

  - stage: Deploy
    displayName: Deploy
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: ubuntu-18.04
        steps:   
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'infra'
            downloadPath: '$(System.DefaultWorkingDirectory)/_artifacts'

        - task: qetza.replacetokens.replacetokens-task.replacetokens@3
          displayName: 'Replace tokens in terraform vars file'
          inputs:
            targetFiles: '$(System.DefaultWorkingDirectory)/_artifacts/infra/**/*.tfvars'
            escapeType: none
            tokenPrefix: '__'
            tokenSuffix: '__'

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
          displayName: 'Install Terraform 0.12.24'
          inputs:
            terraformVersion: 0.12.24

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : init'
          inputs:
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra'
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: 'ado/terraform.tfstate'

        - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV1@0
          displayName: 'Terraform : apply -auto-approve'
          inputs:
            command: apply
            commandOptions: '-auto-approve'
            workingDirectory: '$(System.DefaultWorkingDirectory)/_artifacts/infra'
            environmentServiceNameAzureRM: ${{ variables.ado_service_connection_name }}
            backendServiceArm: ${{ variables.ado_service_connection_name }}
            backendAzureRmResourceGroupName: '$(terraformstoragerg)'
            backendAzureRmStorageAccountName: '$(terraformstorageaccount)'
            backendAzureRmContainerName: terraform
            backendAzureRmKey: 'ado/terraform.tfstate'
