# -----------------------------------------------------------------------------
# .SYNOPSIS
#   This is the main pipeline for ADO Deployment. 
#   The main pipeline will orchestrate the build and deploy to environments. 

# .DESCRIPTION
#   This pipeline will perform setup tasks for the image by:
#   1. Copy and Publish Build Artifacts - Terraform scripts.
#   2. Create Storage Account or Terraform State - https://docs.microsoft.com/en-us/azure/terraform/terraform-backend
#   3. Find and replace token (variables) in .tf and .tfvars files.
#   4. Setup Terraform
#   5. Plan and Apply Terraform

# .ASSUMPTIONS:
#     1. You are referencing this template from an ado pipeline

# .NOTES
#     File Name      : azure-pipelines.yml
#     Prerequisite   : ADO Multi-Stage Yaml Pipeline
# -----------------------------------------------------------------------------

  name: ADO-Infra-$(Date:yyyyMMdd)$(Rev:.r)

  trigger:
    branches:
      include:
      - master
    paths:
      exclude:
        - README.md
        - azure-pipelines.sh
  
  stages: 
  - stage: CI
    displayName: CI
    jobs:
    - template: /pipelines/ci.yaml
      parameters:
        environment: ci
  
  - stage: DEV
    displayName: DEV
    variables:
      - group: ado_dev_vars
    jobs:
    - template: /pipelines/cd.yaml
      parameters:
        environment: DEV
        ado_service_connection_name: $(ado_service_connection_name)
